# --- Serving options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "http://deanattali.com"
baseurl: "thehouseofvitality"

# Brief name and description of the site
title: Acupuncture for Women's Health and Fertility in Thornhill
description: "Acupuncture for Women's Health and Fertility in Thornhill. The House of Vitality also offers Traditional Chinese Medicine modalities for pain relief."

# --- Outputting options --- #
# More information can be found on Jekyll's site
timezone: "America/Toronto"
permalink: /blog/:title/
paginate: 10
paginate_path: "/blog/page:num/"

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Home: "index"
  About: "about"
  Treatments: "treatments"
  Products: "products"
  Blog: "blog"
  Contact: "contact"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Dean Attali
  email: "daattali@gmail.com"
  facebook: daattali
  github: daattali
  twitter: daattali
  linkedin: "pub/dean-attali/8/946/143"
  stackoverflow: "users/3943160/daattali" 
  
# Select which links to show in the footer  
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: true
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "deanattali.com" 

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "deanattali-site"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-59820529-1"  # Your Google Analytics ID

fb_app_id: "536330676521989"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Default YAML values (more information on Jekyll's site)  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts 		
      show-share: true # add sharing buttons to all blog posts		
      show-subscribe: true # add subscribe email to all blog posts
      addthis-plugin: true
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

gems:
  - jekyll-paginate

# 2fc73a3a967e97599c9763d05e564189
